### ISSUE TITLE
Before we go open-source to-do list!

### ISSUE THREAD

**Issue by noahbliss** [Ragarnoy/a121-rs#47]
- [ ] Review licenses we want for the repo
 - [ ] fix ci to use secrets and pull blobs from external repo
- [ ] remove leftover `target` directories
- [ ] remove acconeer blobs from repo and the repo history
